registry: https://registry.npmjs.org/
linkWorkspacePackages: true
packages:
  - 'vendor/*'
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true
minimumReleaseAgeExclude:
  - dsh-map-tools@0.4.4
